name: EasyPromotions
main: me.Arcator.EasyPromotions.Main
description: A fast and easy way to promote someone with a GUI
version: 1.11

commands:
  promote:
    aliases: [easypromote, ep]
    usage: /<command> [user/info/reset]

permissions:
  easypromotions.*:
    description: Gives access to all EasyPromotions commands
    children:
      easypromotions.promote: true
  easypromotions.promote:
    description: Allows a player to promote another to a rank
    default: op