Promotion GUI Name: "&ePromote Duration"
#How often a timer will check for player's role to expire. (In seconds)
TimerCheck: 60
ranks: [mod, admin]
AddRoleCmd: "lp user %user% parent add %rank%"
RemoveRoleCmd: "lp user %user% parent remove %rank%"
messages:
    OnlyPlayers: "&4Error: &cOnly players may use this command!"
    NoPermission: "&4Error: &cYou do not have the permission %permission%"
    InvalidPlayer: "&4Error: &cThat player does not exist."
    InvalidRank: "&4Error: &cThat group is not valid use one of these. &e%ranks%"
    NoEasyPromotion: "&4Error: &cThat player has not been promoted."
    AlreadyPromoted: "&4Error: &cThis player already has a promotion. Use /promote reset {USER} to remove it. Use /promote info {USER} for more detail."
    PromoteMessage: "&e%target%'s rank updated to %rank%"
    ResetMessage: "&e%target%'s rank has been reset."